# Description: Configuration file for CMVDR on real recorded noises.

base: benchmarks/benchmark_base.yaml
noise:
  sig_type: sample
  sample_name: DREGON_individual_motors_recordings_trimmed
cov_estimation:
  cov_est_forgetting_factor: 0.05 # Default: 0.05. Higher beta (forgetting factor): we forget more, therefore more weight to the NEW covariance matrices.