"""
Plot theoretical vs simulated noise reduction factor (η).

This script validates the theoretical noise reduction performance from equation 
eq:res_noise_cmvdr:factor against simulation results using the cMVDR/cMPDR beamformer.

Theoretical formula: η = 1 - ρ² / (1 + σ²ᵢ/σ²ᵥ)
where:
- ρ is the spectral correlation coefficient between harmonic components
- σ²ᵢ is the power of one harmonic component
- σ²ᵥ is the power of another harmonic component (σ²ᵥ > 0 always)

The ratio σ²ᵢ/σ²ᵥ represents the relative power between different harmonic components.

This script uses synthetic covariance matrices with equicorrelated structure
to directly test the beamformer performance without complex signal generation.
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import warnings
import datetime

from cmvdr.beamforming.cyclic_mvdr import CyclicMVDR
from cmvdr.util import utils as u
from cmvdr.util import plotter
from cmvdr.util import globs as gs

# Initialize random number generator
gs.rng, _ = gs.compute_rng(seed_is_random=False, rnd_seed_=42, verbose=True)


def generate_correlated_signal(r_true, sig_shape, cpx_data=True):
    """
    Generate a correlated signal from a given covariance matrix.
    The signal is generated by first generating white noise data, and then multiplying it with the square root of the covariance matrix.
    This method is based on the following reference: https://sefidian.com/2021/12/04/steps-to-sample-from-a-multivariate-gaussian-normal-distribution-with-python-code/
    """

    if np.all(np.diag(r_true) == 0):
        warnings.warn("Real covariance matrix is all zeroes?")
        return np.zeros(sig_shape)

    if r_true.ndim != 2:
        raise ValueError(f"r_true must be a 2D matrix, but {r_true.shape = }")

    # Generate "white" noise data
    if cpx_data:
        v_white = u.circular_gaussian(sig_shape)
    else:
        v_white = gs.rng.standard_normal(size=sig_shape)

    if np.allclose(r_true, np.identity(r_true.shape[0])):
        # If the covariance matrix is the identity matrix, the white noise data is already the correlated signal
        return v_white
    else:
        rv_true_sqrt = cholesky_or_svd(r_true)
        v = rv_true_sqrt @ v_white

    return v


def cholesky_or_svd(r_true):
    try:
        # Introduce correlations between variables by multiplying the white data with the square root of the true noise covariance
        rv_true_sqrt = np.linalg.cholesky(r_true)
    except np.linalg.LinAlgError:
        # Alternative procedure to avoid Cholesky decomposition, which is not defined for singular matrices.
        # (https://stats.stackexchange.com/questions/159313/generating-samples-from-singular-gaussian-distribution)
        warnings.warn("Cholesky decomposition failed. Generating correlated signal using SVD instead.")
        U, d, _ = np.linalg.svd(r_true, hermitian=True)
        assert np.all(
            d >= 0), "Singular values of covariance matrix are negative. Thus this not a valid covariance matrix."
        rv_true_sqrt = U @ np.diag(np.sqrt(d))

    return rv_true_sqrt


def generate_equicorrelated_covariance(rho, P, noise_power=1.0):
    """
    Generate equicorrelated covariance matrix for cyclic processing.
    
    This creates a covariance matrix where all off-diagonal elements have
    correlation ρ, simulating the structure of harmonically-related noise.
    
    Parameters
    ----------
    rho : float
        Correlation coefficient between frequency-shifted components (0 to 1)
    P : int
        Number of cyclic shifts (virtual channels)
    noise_power : float
        Total noise power
        
    Returns
    -------
    ndarray
        (P, P) equicorrelated covariance matrix
    """
    # Create equicorrelated structure: diagonal = 1, off-diagonal = rho
    cov = np.ones((P, P)) * rho
    np.fill_diagonal(cov, 1.0)

    # Scale by noise power
    cov = cov * noise_power

    return cov


def compute_theoretical_eta(rho, sigma_i_to_v_ratio=1.0):
    """
    Calculate theoretical residual noise factor η.
    
    Formula: η = 1 - ρ² / (1 + σ²ᵢ/σ²ᵥ)
    
    Parameters
    ----------
    rho : float or ndarray
        Spectral correlation coefficient |ρ| (0 to 1)
    sigma_i_to_v_ratio : float
        Power ratio σ²ᵢ/σ²ᵥ between harmonic components (default: 1.0, must be > 0)
        
    Returns
    -------
    float or ndarray
        Residual noise factor η
    """
    return 1 - rho ** 2 / (1 + sigma_i_to_v_ratio)


def generate_signal_samples(rho, P, sigma_i_to_v_ratio=1.0, noise_power=1.0, 
                            target_power=1.0, num_samples=1000):
    """
    Generate signal samples for covariance estimation.
    
    Creates samples of target signal, interference, and correlated noise,
    then combines them to form noisy signal samples.
    
    Parameters
    ----------
    rho : float
        Spectral correlation coefficient for noise (0 to 1)
    P : int
        Number of cyclic shifts (virtual channels)
    sigma_i_to_v_ratio : float
        Ratio σ²ᵢ/σ²ᵥ (interference to noise power ratio)
    noise_power : float
        Noise power σ²ᵥ
    target_power : float
        Target signal power
    num_samples : int
        Number of samples to generate (default: 1000)
        
    Returns
    -------
    tuple
        (noisy_samples, noise_samples) both of shape (P, num_samples)
    """

    # Calculate interference power
    interferer_power = sigma_i_to_v_ratio * noise_power
    
    # Generate target signal (white, uncorrelated across frequency shifts)
    # Target is only on the first element (frequency bin)
    target_signal = np.zeros((P, num_samples), dtype=np.complex128)
    target_signal[0, :] = u.circular_gaussian((num_samples,)) * np.sqrt(target_power / 2)

    # Generate interference signal (on second element)
    interference_signal = np.zeros((P, num_samples), dtype=np.complex128)
    if P == 2:
        interference_signal[1, :] = u.circular_gaussian((num_samples,)) * np.sqrt(interferer_power / 2)
    else:
        raise NotImplementedError("Interference generation currently only implemented for P=2. Extend as needed.")
    
    # Generate correlated noise across all frequency shifts
    # Use the equicorrelated covariance structure
    cov_noise = generate_equicorrelated_covariance(rho, P, noise_power)
    noise_signal = generate_correlated_signal(cov_noise, (P, num_samples), cpx_data=True)
    noise_signal = noise_signal * np.sqrt(noise_power / 2)

    # Combine all components
    noisy_signal = target_signal + interference_signal + noise_signal
    
    # Total noise is interference + noise
    total_noise = interference_signal + noise_signal
    
    return noisy_signal, total_noise


def estimate_covariance_batch(signal_samples):
    """
    Estimate covariance matrix from signal samples using batch strategy.
    
    Implements compact version of covariance estimation:
    cov = (signal @ signal.conj().T) / num_samples
    
    Parameters
    ----------
    signal_samples : ndarray
        Signal samples of shape (P, num_samples)
        
    Returns
    -------
    ndarray
        Estimated covariance matrix of shape (P, P)
    """
    num_samples = signal_samples.shape[1]
    
    # Estimate covariance: (signal @ signal^H) / L
    cov_estimated = (signal_samples @ signal_samples.conj().T) / num_samples
    
    return cov_estimated


def compute_empirical_eta_single_bin(rho, P, sigma_i_to_v_ratio=1.0, input_noise_power=1.0, num_samples=1000):
    """
    Compute empirical η using cMVDR beamformer on a single frequency bin.
    
    This function:
    1. Generates signal samples with controlled correlation
    2. Estimates covariances from generated samples using batch strategy
    3. Runs cMVDR beamformer to get optimal weights
    4. Computes output noise power: η = w^H * Φ_n * w / noise_power
    
    Based on the paper, the covariance structure for M=1 with P shifts is:
    S_x = S_s + S_i + S_v
    where:
    - S_s: target signal (targetPow on first element)
    - S_i: interference (interfPow = σ²ᵢ on second element)
    - S_v: noise (noisePow = σ²ᵥ with correlation ρ)
    
    Parameters
    ----------
    rho : float
        Target spectral correlation (0 to 1)
    P : int
        Number of cyclic shifts (virtual channels)
    sigma_i_to_v_ratio : float
        Ratio σ²ᵢ/σ²ᵥ (interference to noise power ratio)
    input_noise_power : float
        Noise power σ²ᵥ (noisePow in the paper)
    num_samples : int
        Number of samples to generate for covariance estimation (default: 1000)
        
    Returns
    -------
    float
        Empirical residual noise factor η
    """
    # For single microphone (M=1), single frequency bin (K=1)
    M = 1
    K = 1
    
    # Target power (arbitrary, doesn't affect η)
    target_power = 1.0
    
    # Generate signal samples
    noisy_samples, total_noise_samples = generate_signal_samples(
        rho, P, sigma_i_to_v_ratio, input_noise_power, target_power, num_samples
    )
    
    # Estimate covariances from generated samples using batch strategy
    cov_noisy_wb = np.zeros((K, M * P, M * P), dtype=np.complex128)
    cov_noise_wb = np.zeros((K, M * P, M * P), dtype=np.complex128)
    
    # Estimate using batch covariance estimation (compact version)
    # cov = (signal @ signal.conj().T) / num_samples
    cov_noisy_wb[0] = estimate_covariance_batch(noisy_samples)
    cov_noise_wb[0] = estimate_covariance_batch(total_noise_samples)
    
    # Narrowband covariances (not used for cyclic bins, but needed for API)
    cov_noise_nb = np.zeros((K, M, M), dtype=np.complex128)
    cov_noisy_nb = np.zeros((K, M, M), dtype=np.complex128)
    
    # Create covariance dictionary
    cov_dict = {
        'noisy_wb': cov_noisy_wb,
        'noise_wb': cov_noise_wb,
        'noisy_nb': cov_noisy_nb,
        'noise_nb': cov_noise_nb
    }

    # Initialize beamformer
    loadings_cfg = (0, 0, 1000)  # (min, max, max_condition_number)
    cm = CyclicMVDR(loadings_cfg, (K, M), minimize_noisy_cov_mvdr=True)

    # Set up harmonic info (all bins are cyclic with P shifts)
    cm.harmonic_info = SimpleHarmonicInfo(K, P_all=np.array([P]))

    # Compute beamformer weights
    cyclic_bins = np.array([0])  # Only one bin, and it's cyclic
    P_all = np.array([P])

    try:
        weights, err_flags, cond_num_cov, sv = cm.compute_cyclic_mvdr_beamformers(
            cov_dict, 'blind', cyclic_bins, P_all=P_all
        )
        
        # Extract weights for the single frequency bin
        w_c = weights[:, 0]  # Shape: (M*P,)
        
        # Compute output noise power: w^H * Φ_n * w
        # Use the estimated noise covariance
        output_noise_power = np.real(np.conj(w_c) @ cov_noise_wb[0] @ w_c)
        
        # Residual noise factor: η = output_noise / input_noise
        eta = output_noise_power / input_noise_power
        
        return eta
        
    except Exception as e:
        print(f"Warning: Beamformer computation failed for rho={rho}, ratio={sigma_i_to_v_ratio}: {e}")
        return 1.0  # Return no noise reduction if failed


class SimpleHarmonicInfo:
    """Minimal harmonic_info for testing."""

    def __init__(self, K, P_all=None):
        self.K = K
        if P_all is None:
            self._P_all = np.ones(K, dtype=int)
        else:
            self._P_all = np.array(P_all, dtype=int)

    def get_num_shifts_all_frequencies(self):
        return self._P_all


def run_simulation_sweep(rho_values, sigma_i_to_v_ratio=1.0, P=8, noise_power=1.0, num_samples=1000):
    """
    Run simulation sweep over correlation values.
    
    Parameters
    ----------
    rho_values : array_like
        Array of spectral correlation values to test
    sigma_i_to_v_ratio : float
        Ratio σ²ᵢ/σ²ᵥ (interference to noise power ratio)
    P : int
        Number of cyclic shifts (virtual channels)
    noise_power : float
        Input noise power
    num_samples : int
        Number of samples to generate for covariance estimation (default: 1000)
        
    Returns
    -------
    ndarray
        Array of empirical η values
    """
    eta_empirical = []
    
    for rho in rho_values:
        eta = compute_empirical_eta_single_bin(rho, P, sigma_i_to_v_ratio, noise_power, num_samples)
        eta_empirical.append(eta)
    
    return np.array(eta_empirical)


def create_plot_multi(rho_theory, eta_theory_dict, sigma_ratios, rho_sim, eta_sim_dict, output_path, use_db=False):
    """
    Create comparison plot with multiple theoretical curves for different σ²ᵢ/σ²ᵥ ratios.
    
    Parameters
    ----------
    rho_theory : ndarray
        Theoretical correlation values (dense, for smooth curves)
    eta_theory_dict : dict
        Dict mapping σ²ᵢ/σ²ᵥ ratios to theoretical η arrays
    sigma_ratios : list
        List of σ²ᵢ/σ²ᵥ ratios to plot
    rho_sim : ndarray
        Simulation correlation values (sparse, for markers)
    eta_sim_dict : dict
        Dict mapping σ²ᵢ/σ²ᵥ ratios to empirical η arrays from simulation
    output_path : Path
        Output file path
    use_db : bool
        If True, plot in dB scale
    """
    # Check if LaTeX is available
    use_latex = plotter.is_tex_plotting_available()
    if not use_latex:
        print("   LaTeX not available, using standard matplotlib rendering")

    # Set plot options based on LaTeX availability
    u.set_plot_options(use_tex=use_latex)

    # Use proper figure size for double-column LaTeX documents
    width = u.get_plot_width_double_column_latex()
    height = width * 0.75  # Aspect ratio

    fig, ax = plt.subplots(figsize=(width, height))

    # Color scheme for different ratios
    colors = ['tab:blue', 'tab:orange', 'tab:green', 'tab:red']
    markers = ['o', 's', '^', 'D']

    # Plot theory curves and simulation markers for each σ²ᵢ/σ²ᵥ ratio
    for idx, ratio in enumerate(sigma_ratios):
        eta_theory = eta_theory_dict[ratio]

        if use_db:
            eta_theory_plot = 10 * np.log10(eta_theory + 1e-10)
        else:
            eta_theory_plot = eta_theory

        color = colors[idx % len(colors)]
        marker = markers[idx % len(markers)]

        if use_latex:
            label_theory = r'Theory: $\sigma_i^2/\sigma_v^2 = ' + f'{ratio:.2g}' + r'$'
            label_sim = r'Sim: $\sigma_i^2/\sigma_v^2 = ' + f'{ratio:.2g}' + r'$'
        else:
            label_theory = f'Theory: σ²ᵢ/σ²ᵥ = {ratio:.2g}'
            label_sim = f'Sim: σ²ᵢ/σ²ᵥ = {ratio:.2g}'

        # Plot theory line
        ax.plot(rho_theory, eta_theory_plot,
                color=color, linestyle='-', linewidth=1.5,
                label=label_theory)

        # Plot simulation markers with same color
        if ratio in eta_sim_dict:
            eta_sim = eta_sim_dict[ratio]
            if use_db:
                eta_sim_plot = 10 * np.log10(eta_sim + 1e-10)
            else:
                eta_sim_plot = eta_sim

            ax.plot(rho_sim, eta_sim_plot,
                    color=color, marker=marker, linestyle='',
                    markersize=4, markerfacecolor='none', markeredgewidth=1.0,
                    label=label_sim)

    if use_db:
        ylabel = r'$\eta$ (dB)' if use_latex else 'η (dB)'
    else:
        ylabel = r'$\eta$' if use_latex else 'η'

    ax.set_xlabel(r'Spectral correlation $|\rho|$' if use_latex else 'Spectral correlation |ρ|')
    ax.set_ylabel(ylabel)

    if use_latex:
        ax.set_title(r'Noise Reduction Factor $\eta$ vs.\ Correlation')
    else:
        ax.set_title('Noise Reduction Factor η vs. Correlation')

    ax.grid(True, alpha=0.3)
    ax.legend(loc='best', fontsize=7, ncol=2)
    ax.set_xlim([0, 1])

    plt.tight_layout()

    # Save figure
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"   Figure saved to: {output_path}")

    # Also save as PDF
    pdf_path = output_path.with_suffix('.pdf')
    fig.savefig(pdf_path, bbox_inches='tight')
    print(f"   PDF saved to: {pdf_path}")

    plt.close(fig)

    return fig


def create_plot(rho_theory, eta_theory, rho_sim, eta_sim, output_path, use_db=False):
    """
    Create comparison plot of theoretical vs simulated noise reduction.
    
    Parameters
    ----------
    rho_theory : ndarray
        Theoretical correlation values (dense, for smooth curves)
    eta_theory : ndarray
        Theoretical η values
    rho_sim : ndarray
        Simulation correlation values (sparse, for markers)
    eta_sim : ndarray
        Empirical η values from simulation
    output_path : Path
        Output file path
    use_db : bool
        If True, plot in dB scale
    """
    # Check if LaTeX is available
    use_latex = plotter.is_tex_plotting_available()
    if not use_latex:
        print("   LaTeX not available, using standard matplotlib rendering")

    # Set plot options based on LaTeX availability
    u.set_plot_options(use_tex=use_latex)

    # Use proper figure size for double-column LaTeX documents
    width = u.get_plot_width_double_column_latex()
    height = width * 0.75  # Aspect ratio

    fig, ax = plt.subplots(figsize=(width, height))

    # Plot theory (solid line)
    if use_db:
        eta_theory_plot = 10 * np.log10(eta_theory + 1e-10)
        eta_sim_plot = 10 * np.log10(eta_sim + 1e-10)
        ylabel = r'$\eta$ (dB)' if use_latex else 'η (dB)'
    else:
        eta_theory_plot = eta_theory
        eta_sim_plot = eta_sim
        ylabel = r'$\eta$' if use_latex else 'η'

    ax.plot(rho_theory, eta_theory_plot,
            color='tab:blue', linestyle='-', linewidth=1.5,
            label='Theory')

    # Plot simulation (markers)
    ax.plot(rho_sim, eta_sim_plot,
            color='tab:orange', marker='o', linestyle='',
            markersize=6, markerfacecolor='none', markeredgewidth=1.5,
            label='Simulation (cMVDR)')

    ax.set_xlabel(r'Spectral correlation $|\rho|$' if use_latex else 'Spectral correlation |ρ|')
    ax.set_ylabel(ylabel)

    if use_latex:
        ax.set_title(r'Noise Reduction Factor $\eta$ vs.\ Correlation')
    else:
        ax.set_title('Noise Reduction Factor η vs. Correlation')

    ax.grid(True, alpha=0.3)
    ax.legend(loc='best')
    ax.set_xlim([0, 1])

    plt.tight_layout()

    # Save figure
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300, bbox_inches='tight')
    print(f"   Figure saved to: {output_path}")

    # Also save as PDF
    pdf_path = output_path.with_suffix('.pdf')
    fig.savefig(pdf_path, bbox_inches='tight')
    print(f"   PDF saved to: {pdf_path}")

    plt.close(fig)

    return fig


def main():
    """Main execution function."""

    print("=" * 60)
    print("Noise Reduction Factor η vs Correlation")
    print("=" * 60)

    # Configuration parameters
    P = 8  # Number of cyclic shifts (virtual channels)
    noise_power = 1.0
    num_samples = 1000  # Number of samples for covariance estimation

    # Test multiple σ²ᵢ/σ²ᵥ ratios (power ratios between harmonic components)
    sigma_ratios = [0.01, 0.1, 1, 10]
    
    # Dense sampling for theory (smooth curves)
    rho_theory = np.linspace(0, 0.99, 100)

    # Sparse sampling for simulation (markers)
    rho_sim = np.linspace(0, 0.99, 15)

    # Compute theoretical curves for different ratios
    print("\n1. Computing theoretical η curves for different σ²ᵢ/σ²ᵥ ratios...")
    eta_theory_dict = {}
    for ratio in sigma_ratios:
        eta_theory_dict[ratio] = compute_theoretical_eta(rho_theory, sigma_i_to_v_ratio=ratio)
        print(
            f"   σ²ᵢ/σ²ᵥ = {ratio:5.2f}: η range [{eta_theory_dict[ratio].min():.4f}, {eta_theory_dict[ratio].max():.4f}]")

    # Run simulations for EACH ratio configuration
    print("\n2. Running cMVDR simulations for each σ²ᵢ/σ²ᵥ ratio...")
    print(f"   Using P={P} cyclic shifts")

    eta_sim_dict = {}
    for ratio in sigma_ratios:
        print(f"   Processing σ²ᵢ/σ²ᵥ = {ratio:5.2f}...")
        eta_sim_dict[ratio] = run_simulation_sweep(rho_sim, sigma_i_to_v_ratio=ratio, P=P, 
                                                   noise_power=noise_power, num_samples=num_samples)
        print(f"      Simulation: η range [{eta_sim_dict[ratio].min():.4f}, {eta_sim_dict[ratio].max():.4f}]")

    # Create output directory
    today = datetime.date.today().isoformat()
    output_dir = Path(__file__).parent.parent / 'figs' / f'{today}_eta_vs_correlation'
    output_dir.mkdir(parents=True, exist_ok=True)

    # Generate plots
    print("\n3. Generating plots...")

    # Linear scale plot with multiple theory curves and simulations
    output_path_linear = output_dir / 'eta_vs_correlation_multi_linear.png'
    fig_linear = create_plot_multi(
        rho_theory, eta_theory_dict, sigma_ratios,
        rho_sim, eta_sim_dict,
        output_path_linear,
        use_db=False
    )

    # dB scale plot with multiple theory curves and simulations
    output_path_db = output_dir / 'eta_vs_correlation_multi_db.png'
    fig_db = create_plot_multi(
        rho_theory, eta_theory_dict, sigma_ratios,
        rho_sim, eta_sim_dict,
        output_path_db,
        use_db=True
    )

    print("\n" + "=" * 60)
    print("Completed successfully!")
    print("=" * 60)


if __name__ == '__main__':
    main()
