## Description: Default configuration for the cyclic beamforming experiments.
secondary_config_file: cmvdr.yaml  # change to cmvdr.yaml for the full set of experiments

seed_is_random: 0
seed_if_not_random: 12345

data_type: synthetic
data_types_all: [synthetic, instruments, speech, synthetic_f0_err, plot_spectrograms, demo]

print_results: 1
plot:
  destination:                  'debug'  # alternatives are debug, slides, paper
  destination_final_results:    'paper'  # debug, slides, paper
  intermediate_results:         0
  spectrograms:                 0
  all_variations:               0
  f0_spectrogram:               0
  error_per_frequency:          0
  separately:                   0
  waveforms:            false

fs: 16000